<h1>Introduction to NumPy</h1>

<h4>NumPy - short for Numerical Python - Provides an efficient interface to store and operate on dense data buffers.</h4>

In [2]:
# Import numpy and check version
# Using as is the mechanism to alias the import.
import numpy as np
np.__version__

'1.23.5'

In [5]:
# All the contents of the numpy namespace can be obtained by using dot operator with tab key
np.abs

<ufunc 'absolute'>

In [6]:
# To diplay numpy's built in documentation
np?

In [7]:
# Python provides dynamic typing - thus allowing skipping of declaration of each variable
result = 0
for i in range(100):
    result += i
    
# This leads in python to assign any kind of data to any kind of variable 
x = 4
x = "four"
print(x)

four


In [11]:
# A standard python implementation is written in C
# A python integer is a pointer to a position in memory containing all the Python objetc information, 
# including the bytes that contain the integer value. This extra information in the python integer structures
# is what allows python to be coded so freely and dynamically. 
int??

<h1>Python List</h1>

In [13]:
L = list(range(10))
print(L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [14]:
# type function to get the type of list
print(type(L))

<class 'list'>


In [15]:
# type function to get the type of list element
print(type(L[0]))

<class 'int'>


In [16]:
# A list of strings
L2 = [str(c) for c in L]
print(L2)

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


In [17]:
# Using type function to get the type of List and type of element in List
print(type(L2))
print(type(L2[0]))

<class 'list'>
<class 'str'>


In [18]:
# As python is dynamically typed language, lists can be heterogeneous
# To allow these flexible types each item in the list must contain its own type info
# reference count and other information. That is each item is a complete Python Object.
L3 = [True, "2",3.0,4]
print(L3)

[True, '2', 3.0, 4]


In [19]:
# Use type function to get the type of each element in the list l3
[type(item) for item in L3]

[bool, str, float, int]

<h1>Fixed type arrays in Python</h1>

In [22]:
# The built in array module can be used to create dense arrays of a uniform type
import array
L = list(range(10))
A = array.array('i',L)  # i is type code indicating the elements are integers
print(A)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


<h1>Ways of creating Numpy Array</h1>

In [23]:
import numpy as np

<h3>Creating Arrays from Python Lists</h3>

In [27]:
# use np.array to create arrays from python lists
A = np.array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [28]:
# If types do not match, Numpy will upcast if possible 
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [29]:
# Use dtype keyword to explicitly set the data type of the resulting numpy array
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [30]:
# Numpy arrays can be explicitly multi-dimensional
# One way of initializing a multi-dimensional array using list of lists
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

<h3>Creating arrays from scratch</h3>

In [31]:
# it is more efficient to create arrays from scratch using routines built into NumPy
# create a length -10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
# Create a 3X5 floating point array filled with 1s
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
# Create a 3X5 array filled with 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [34]:
# Create an array filled with linear sequence starting from 0 ending at 20 
# stepping by 2. 
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [35]:
# Create an array of evenyl spaced values between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [42]:
# Create a 3x3 array of uniformly distributed random values between 0 and 1
np.random.random((3,3))

array([[0.51414659, 0.96943926, 0.78320892],
       [0.42210716, 0.21468669, 0.69974686],
       [0.66552496, 0.90790451, 0.33571719]])

In [43]:
# Create a 1x3 array of uniformly distributed random values between 0 and 1
np.random.random((1,3))

array([[0.45857434, 0.82718701, 0.18583942]])

In [44]:
# Create a 3x3 array of normally distributed random values with mean 0 and standard deviation 1
np.random.normal(0, 1, (3,3))

array([[-1.8818587 , -1.17566424, -0.8923065 ],
       [-1.55017276,  0.31881443, -0.55673689],
       [ 1.3002756 , -1.128353  , -0.53203171]])

In [45]:
# Create a 3 x 3 array of random integers in the interval [0,10]
np.random.randint(0,10,(3,3))

array([[5, 2, 1],
       [3, 8, 8],
       [4, 4, 9]])

In [46]:
# Create an array of 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
# Create an uninitialized array of three integers
np.empty(3)

array([1., 1., 1.])

In [48]:
# When creating an array, data type can be specified using a string
np.zeros(10, dtype="int16")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [49]:
# The above can also be achieved as below:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [50]:
# The same can be achieved as below as well for floats
np.zeros(10, dtype=np.float16)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float16)