<h1>Computations on Numpy arrays</h1>

In [1]:
# Looping over arrays to operate on each element
import numpy as np
np.random.seed(0)

In [3]:
# Definition of compute reciprocals method
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output

values = np.random.randint(1,10, size=5)
output = compute_reciprocals(values)
output

array([0.25      , 0.16666667, 0.33333333, 0.2       , 0.125     ])

In [4]:
# Use timeit function to time the call to big arrya
big_array = np.random.randint(1,100,size=1000000)
%timeit compute_reciprocals(big_array)

787 ms ± 10.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


<h3>Vectorized Operation: Numpy provides statically typed, compute routine known as vectorized operation.</h3>

In [5]:
# Vectorized approach is designed to push the loop into the compiled layer that underlies numpy, 
# leading to much faster execution.
print(compute_reciprocals(values))
print(1.0/values)

[0.25       0.16666667 0.33333333 0.2        0.125     ]
[0.25       0.16666667 0.33333333 0.2        0.125     ]


In [6]:
# Timing the operation is suggesting that it completes orders of magnitude faster than python loop
%timeit (1.0/big_array)

702 µs ± 6.01 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [7]:
# Vectorized operations in NumPy are implemented via ufuncs, whose main purpose is to quickly execute repeated
# operations on values in NumPy arrays
# Ufuncs are very flexible. 
np.arange(5)/np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [8]:
# ufunc operations are not limited to one dimensional arrays. They can act on multi-dimensional arrays as well. 
x = np.arange(9).reshape(3,3)
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

<h3> NumPy Ufuncs</h3>

In [10]:
# Ufuncs exist in two flavors: unary ufuncs working on single input and binary ufuncs working on two inputs
x = np.arange(4)
print("x     =",x)
print("x + 5 =",x + 5)
print("x - 5 =",x - 5)
print("x * 2 =",x * 2)
print("x/2   =",x/2)
print("x//2  =",x//2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x/2   = [0.  0.5 1.  1.5]
x//2  = [0 0 1 1]


In [11]:
# Unary ufunc for negation, a ** exponentiation and a % operator for modulus. 
print("-x.   =",-x)
print("x ** 2=",x**2)
print("x %  2=",x%2)

-x.   = [ 0 -1 -2 -3]
x ** 2= [0 1 4 9]
x %  2= [0 1 0 1]


In [12]:
# In addition these can be strung together however you wish, and the standard order of operations is maintained. 
-(0.5 * x + 1) **2

array([-1.  , -2.25, -4.  , -6.25])

In [13]:
# All of these arithmetic operations are convenient wrappers around specific functions built into NumPy.
# + operator is wrapper for add function
np.add(x,2)

array([2, 3, 4, 5])

In [14]:
# - operator is wrapper for subtract function
np.subtract(x,2)

array([-2, -1,  0,  1])

In [15]:
# Unary negation is wrapper for negative functions
np.negative(x)

array([ 0, -1, -2, -3])

In [16]:
# * operator is wrapper for multiplication function
np.multiply(x,2)

array([0, 2, 4, 6])

In [17]:
# / operator is wrapper for divide function
np.divide(x,2)

array([0. , 0.5, 1. , 1.5])

In [18]:
# // operator is wrapper for floor divide function
np.floor_divide(x,2)

array([0, 0, 1, 1])

In [19]:
# ** operator is wrapper for exponentiation function
np.power(x,2)

array([0, 1, 4, 9])

In [20]:
# % operaotr is wrapper for modulus function
np.mod(x,2)

array([0, 1, 0, 1])

<h4>Absolute Function</h4>

In [21]:
# Numpy understands Python's built-in absolute vaue function
x = np.array([-2,-1,0,1,2])
abs(x)

array([2, 1, 0, 1, 2])

In [22]:
# Corresponding Numpy function is as :
np.absolute(x)

array([2, 1, 0, 1, 2])

In [23]:
# Same function can also be written using alias as abs
np.abs(x)

array([2, 1, 0, 1, 2])

In [24]:
# Ufunc can handle complex data as well, in which absolute value returns the magnitude
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

<h4>Trignometric Functions</h4>

In [25]:
# Define an array of angles
theta = np.linspace(0, np.pi, 3)
print("Theta is ", theta)

# Compute trignometric functions on these values
print("sin(theta)", np.sin(theta))
print("cos(theta)", np.cos(theta))
print("tan(theta)", np.tan(theta))

Theta is  [0.         1.57079633 3.14159265]
sin(theta) [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [26]:
# Inverse trignometric functions are also available
x = [-1, 0, 1]

print("x   = ", x)
print("arcsin(x)", np.arcsin(x))
print("arccos(x)", np.arccos(x))
print("arctan(x)", np.arctan(x))

x   =  [-1, 0, 1]
arcsin(x) [-1.57079633  0.          1.57079633]
arccos(x) [3.14159265 1.57079633 0.        ]
arctan(x) [-0.78539816  0.          0.78539816]


<h4>Exponents and logarithms </h4>

In [27]:
# Exponentials
x = [1,2,3]

print("x  =",x)
print("e^x  =",np.exp(x))
print("2^x  =",np.exp2(x))
print("3^x  =",np.power(3,x))

x  = [1, 2, 3]
e^x  = [ 2.71828183  7.3890561  20.08553692]
2^x  = [2. 4. 8.]
3^x  = [ 3  9 27]


In [28]:
# Inverse of exponentials that is logarithm are also available

x = [1,2,4,10]
print("x  =",x)
print("ln(x)  =",np.log(x))
print("log2(x)  =",np.log2(x))
print("log10(x)  =",np.log10(x))

x  = [1, 2, 4, 10]
ln(x)  = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x)  = [0.         0.30103    0.60205999 1.        ]


In [30]:
# Specialized versions that are useful for maintaining precision with very small input
x = [0, 0.001, 0.01, 0.1]

print("Exponential of x - 1=", np.expm1(x))
print("log(1+x) = ", np.log1p(x))

# When x is very small these functions give more precise values than if the raw np.log or np.exp were used. 

Exponential of x - 1= [0.         0.0010005  0.01005017 0.10517092]
log(1+x) =  [0.         0.0009995  0.00995033 0.09531018]


<h4>Specialized Ufuncs</h4>

In [31]:
# If you compute some obscure mathematical function on your data it is implmented in scipy.special. 
# Importing of this is done as follows
from scipy import special

In [32]:
# Gamma Functions generalized factorials and related functions
x = [1,5,10]

print("gamma of x = ",special.gamma(x))
print("ln|gamma(x) = ", special.gammaln(x))
print("beta(x,2) = ", special.beta(x,2))

gamma of x =  [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x) =  [ 0.          3.17805383 12.80182748]
beta(x,2) =  [0.5        0.03333333 0.00909091]


In [33]:
# Error function (integral of gaussian) its complement and ints inverse
x = np.array([0, 0.3, 0.7, 1.0])

print("erf(x) =",special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

erf(x) = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


<h3>Advanced Ufunc features </h3>

In [34]:
# Specifying output - For large calculations it is useful to be ablet to specify the array where the result of
# the function can be stored. 

# Rather than creating temporary array, you can use this to write computation results to the memory location 
# where you would like them to be. 

# For all ufuncs this can be done using the out argument of the function:
x = np.arange(5)
y = np.empty(5)
np.multiply(x,10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [36]:
# This can be used with array views. For example, we can write the results of a computation to every other element 
# of a specified array. 

y = np.zeros(10)
np.power(2,x,out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


<h4>Aggregates</h4>

In [37]:
# A reduce repeatedly applies a given operation to the elements of the array until only a single result remains. 
x = np.arange(1,6)
print(x)
print(np.add.reduce(x))

[1 2 3 4 5]
15


In [39]:
# Reduce function on the product of all array 
print(np.multiply.reduce(x))

120


In [40]:
# store all intermediate results of the computation
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [41]:
# store all intermediate results of the computation of multiplication
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

<h4>Outer Products</h4>

In [42]:
# Any ufunc can compute the output of all pairs of two different inputs using the outer method
x = np.arange(1,6)
np.multiply.outer(x,x)

# Broadcasting - Ability to operate between arrays of different shapes and sizes.

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [43]:
# Generate documentation and gain all the information about a package and its methods.
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    ``arange`` can be called with a varying number of positional arguments:
    
    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.
    
    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.
    
    S